#!/bin/sh
uci set gluon-node-info.@location[0]='location'
uci set gluon-node-info.@location[0].share_location='1'
uci set gluon-node-info.@location[0].latitude='47.558845'
uci set gluon-node-info.@location[0].longitude='7.932065'
uci commit gluon-node-info.@location[0]
