#!/bin/sh
uci set gluon-node-info.@location[0]='location'
uci set gluon-node-info.@location[0].share_location='1'
uci set gluon-node-info.@location[0].latitude='47.554918'
uci set gluon-node-info.@location[0].longitude='7.933025'
uci commit
